DATA_DIR = '../data/VCTK-Corpus/samples'
FOLDER_WAV = 'wav48'
FOLDER_TXT = 'txt'

SUMMARIES_DIR = 'tmp'

TRAINING_SIZE = 2

WINDOW_SIZE_MS = 30.0
WINDOW_STRIDE_MS = 10.0
DCT_COEFFICIENT_COUNT = 40

SAMPLE_RATE = 16000

BATCH_SIZE = 2